package com.mapbox.navigation.ui.maneuver.model

internal enum class LaneTurns {
    LANE_UTURN,
    LANE_RIGHT,
    LANE_LEFT,
    LANE_STRAIGHT,
    LANE_SHARP_LEFT,
    LANE_SLIGHT_LEFT,
    LANE_SHARP_RIGHT,
    LANE_SLIGHT_RIGHT,
    LANE_LEFT_STRAIGHT_LEFT_ONLY,
    LANE_RIGHT_STRAIGHT_RIGHT_ONLY,
    LANE_LEFT_STRAIGHT_STRAIGHT_ONLY,
    LANE_RIGHT_STRAIGHT_STRAIGHT_ONLY,
    LANE_SLIGHT_LEFT_STRAIGHT_SLIGHT_LEFT_ONLY,
    LANE_SLIGHT_RIGHT_STRAIGHT_SLIGHT_RIGHT_ONLY,
    LANE_SLIGHT_LEFT_STRAIGHT_STRAIGHT_ONLY,
    LANE_SLIGHT_RIGHT_STRAIGHT_STRAIGHT_ONLY,
    LANE_SHARP_LEFT_STRAIGHT_SHARP_LEFT_ONLY,
    LANE_SHARP_RIGHT_STRAIGHT_SHARP_RIGHT_ONLY,
    LANE_SHARP_LEFT_STRAIGHT_STRAIGHT_ONLY,
    LANE_SHARP_RIGHT_STRAIGHT_STRAIGHT_ONLY,
}
