version: 2

workflows:
  version: 2
  default:
    jobs:
      - build
      - release
      - publish:
          filters:
            tags:
              only: /^testapp-.*/
            branches:
              ignore: /.*/
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: mbgl/61abee1674:android-ndk-r18
    environment:
      JVM_OPTS: -Xmx3200m
      BUILDTYPE: Debug
      IS_LOCAL_DEVELOPMENT: false
      GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Check Java code style
          command: make checkstyle
      - run:
          name: Run unit-test, generate Jacoco test report and Post code coverage report to Codecov.io
          command: |
            ./gradlew testDebugUnitTestCoverage
            pip install --user codecov && /root/.local/bin/codecov
      - run:
          name: Build release to test ProGuard rules
          command: ./gradlew app:assembleRelease
      - run:
          name: Build Test Application APK
          command: |
            ./gradlew accessToken
            ./gradlew app:assembleDebug
      - run:
          name: Build Instrumentation Test APK
          command: |
            ./gradlew app:assembleAndroidTest
      - run:
          name: Log in to Google Cloud Platform
          shell: /bin/bash -euo pipefail
          command: |
            echo "${GCLOUD_SERVICE_ACCOUNT_JSON}" > secret.json
            gcloud auth activate-service-account --key-file secret.json --project mapbox-navigation-android
            rm secret.json
      - run:
          name: Run instrumentation tests on Firebase
          no_output_timeout: 1200
          shell: /bin/bash -euo pipefail
          command: |
            gcloud firebase test android run --type instrumentation \
              --app app/build/outputs/apk/debug/app-debug.apk \
              --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --device model=hammerhead,version=21,locale=en,orientation=portrait  \
              --device model=athene,version=23,locale=fr,orientation=landscape \
              --device model=sailfish,version=26,locale=es,orientation=portrait \
              --device model=walleye,version=28,locale=de,orientation=landscape \
              --timeout 5m
      - run:
          name: Run robo test on Firebase
          no_output_timeout: 1200
          shell: /bin/bash -euo pipefail
          command: |
            gcloud firebase test android run --type robo \
              --app app/build/outputs/apk/debug/app-debug.apk \
              --device-ids shamu \
              --os-version-ids 22 \
              --locales en \
              --orientations portrait \
              --timeout 5m
      - run:
          name: Update Transifex
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              pip install transifex-client
              echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"${TRANSIFEX_USER}"$'\npassword = '"${TRANSIFEX_API_TOKEN}"$'\ntoken = '""$'\n' > ~/.transifexrc
              tx push -s
            else
              echo "Skipping push to Transifex"
            fi
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

# ------------------------------------------------------------------------------
  release:
    branch:
      only:
      - master
    docker:
      - image: mbgl/61abee1674:android-ndk-r18
    working_directory: ~/code
    environment:
      BUILDTYPE: Release
      IS_LOCAL_DEVELOPMENT: false
    steps:
      - checkout
      - run:
          name: Generate Maven credentials
          shell: /bin/bash -euo pipefail
          command: |
            aws s3 cp s3://mapbox/android/signing-credentials/secring.gpg secring.gpg
            echo "NEXUS_USERNAME=$PUBLISH_NEXUS_USERNAME
            NEXUS_PASSWORD=$PUBLISH_NEXUS_PASSWORD
            signing.keyId=$SIGNING_KEYID
            signing.password=$SIGNING_PASSWORD
            signing.secretKeyRingFile=../secring.gpg" >> gradle.properties
      - run:
          name: Build Navigation SDK
          command: make build-release
      - deploy:
          name: Publish Navigation SDK To Maven Central
          command: |
            if [ "${CIRCLE_BRANCH}" == "dan-offline-maps-ui" ]; then
            make publish ;
            fi
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Environment
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Check & Publish Binary Size
          command: |
            ./scripts/check_binary_size.sh ./scripts/paths_file.txt ./scripts/labels_file.txt 'mapbox-navigation-android' 'android' ./scripts/sdks_file.txt "${CIRCLE_SHA1}"
# ------------------------------------------------------------------------------
  publish:
    docker:
      - image: mbgl/61abee1674:android-ndk-r18
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
      BUILDTYPE: Debug
      IS_LOCAL_DEVELOPMENT: false
      GOOGLE_PLAY_TRACK: internal
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Export Google Play authentication json
          command: |
            #!/bin/bash
            echo "${MAPBOX_DEVELOPER_CONFIG}" > /root/code/app/src/main/res/values/developer-config.xml
            echo "${PLAY_PUBLISH_AUTH_JSON}" > android-gl-native-15d95ab30d0f.json
      - run:
          name: Crashlytics setup
          command: |
            #!/bin/bash
            echo "apply plugin: 'io.fabric'" >> /root/code/app/build.gradle
            echo "apply plugin: 'com.google.gms.google-services'" >> /root/code/app/build.gradle
            echo "${GOOGLE_SERVICES_JSON}" > /root/code/app/google-services.json
      - run:
          name: Release to Google Play
          command: ./gradlew :app:publishRelease
# ------------------------------------------------------------------------------
