version: 2.1
parameters:
  docker-image-tag:
    type: string
    default: "mbgl/android-ndk-r21:769c31f1d8"

workflows:
  version: 2
  default:
    jobs:
      - assemble-debug
      - assemble-release
      - static-analysis:
          requires:
            - assemble-debug
      - unit-tests:
          requires:
            - assemble-debug
      - ui-robo-tests:
          requires:
            - assemble-release
            - assemble-debug
            - static-analysis
            - unit-tests
      - ui-instrumentation-tests:
          requires:
            - assemble-release
            - assemble-debug
            - static-analysis
            - unit-tests
      - release-snapshot:
          filters:
            branches:
              only:
                - master
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

commands:
  restore-gradle-cache:
    steps:
      - restore_cache:
          keys:
            - deps-{{ checksum "build.gradle" }}-{{ checksum  "gradle/dependencies.gradle" }}-{{ checksum  "examples/build.gradle" }}-{{ checksum  "libnavigation-router/build.gradle" }}-{{ checksum  "libnavigation-base/build.gradle" }}-{{ checksum  "libnavigation-core/build.gradle" }}-{{ checksum  "libnavigation-metrics/build.gradle" }}-{{ checksum  "libnavigation-util/build.gradle" }}-{{ checksum  "libnavigator/build.gradle" }}-{{ checksum  "libtrip-notification/build.gradle" }}-{{ checksum  "libtesting-ui/build.gradle" }}-{{ checksum  "libtesting-utils/build.gradle" }}-{{ checksum  "libnavigation-ui/build.gradle" }}
            - deps-
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: deps-{{ checksum "build.gradle" }}-{{ checksum  "gradle/dependencies.gradle" }}-{{ checksum  "examples/build.gradle" }}-{{ checksum  "libnavigation-router/build.gradle" }}-{{ checksum  "libnavigation-base/build.gradle" }}-{{ checksum  "libnavigation-core/build.gradle" }}-{{ checksum  "libnavigation-metrics/build.gradle" }}-{{ checksum  "libnavigation-util/build.gradle" }}-{{ checksum  "libnavigator/build.gradle" }}-{{ checksum  "libtrip-notification/build.gradle" }}-{{ checksum  "libtesting-ui/build.gradle" }}-{{ checksum  "libtesting-utils/build.gradle" }}-{{ checksum  "libnavigation-ui/build.gradle" }}

  verify:
    steps:
      - run:
          name: Check codebase
          command: make check

  assemble-module:
    parameters:
      module_target:
        description: module target
        type: string
      variant:
        description: debug or release
        type: string
    steps:
      - run:
          name: Assemble << parameters.module_target >> APK in << parameters.variant >> mode
          command: |
            ./gradlew << parameters.module_target >>:assemble<< parameters.variant >>

  assemble-example-app:
    parameters:
      variant:
        description: debug or release
        type: string
    steps:
      - run:
          name: Assemble examples APK in << parameters.variant >> mode
          command: |
            echo "${MAPBOX_DEVELOPER_CONFIG}" > /root/code/examples/src/main/res/values/mapbox_access_token.xml
            ./gradlew examples:assemble<< parameters.variant >>

  assemble-instrumentation-test:
    parameters:
      module_target:
        description: module target
        type: string
    steps:
      - run:
          name: Assemble Instrumentation Test APK
          command: |
            ./gradlew << parameters.module_target >>:assembleAndroidTest

  login-google-cloud-platform:
    steps:
      - run:
          name: Log in to Google Cloud Platform
          shell: /bin/bash -euo pipefail
          command: |
            echo "${GCLOUD_SERVICE_ACCOUNT_JSON}" > secret.json
            gcloud auth activate-service-account --key-file secret.json --project mapbox-navigation-android
            rm secret.json

  store-results:
    parameters:
      module_target:
        description: module target
        type: string
    steps:
      - store_artifacts:
          path: << parameters.module_target >>/build/reports
          destination: << parameters.module_target >>/reports
      - store_test_results:
          path: << parameters.module_target >>/build/test-results

  assemble-core-debug:
    steps:
      - run:
          name: Assemble Navigation Core SDK (debug)
          command: make assemble-core-debug

  assemble-ui-debug:
    steps:
      - run:
          name: Assemble Navigation UI SDK(debug)
          command: make assemble-ui-debug

  assemble-core-release:
    steps:
      - run:
          name: Assemble Navigation Core SDK (release)
          command: make assemble-core-release

  assemble-ui-release:
    steps:
      - run:
          name: Assemble Navigation UI SDK (release)
          command: make assemble-ui-release

  check-api-core:
    steps:
      - run:
          name: Check Navigation Core SDK public API
          command: |
            make assemble-core-release
            make core-check-api

  check-api-ui:
    steps:
      - run:
          name: Check Navigation UI SDK public API
          command: |
            make assemble-ui-release
            make ui-check-api

  unit-tests-core:
    steps:
      - run:
          name: Run Navigation Core SDK Unit Tests and generate Jacoco test report
          command: |
            make core-unit-tests-jacoco
      - store-results:
          module_target: "libnavigation-router"
      - store-results:
          module_target: "libnavigation-base"
      - store-results:
          module_target: "libnavigation-core"
      - store-results:
          module_target: "libnavigation-metrics"
      - store-results:
          module_target: "libnavigation-util"
      - store-results:
          module_target: "libnavigator"
      - store-results:
          module_target: "libtrip-notification"

  unit-tests-ui:
    steps:
      - run:
          name: Run Navigation UI SDK Unit Tests and generate Jacoco test report
          command: |
            make ui-unit-tests-jacoco
      - store-results:
          module_target: "libnavigation-ui"

  codecov:
    steps:
      - run:
          name: Post code coverage reports to Codecov.io
          command: pip install --user codecov && /root/.local/bin/codecov

  generate-version-name:
    steps:
      - run:
          name: Generate Core version name
          command: |
            if [[ -n "$CIRCLE_TAG" ]]; then
              if [[ $CIRCLE_TAG == v* ]]; then
                POM_VERSION_NAME=`echo $CIRCLE_TAG | sed s/v//`
              else
                echo "Exiting the job as this is not a release TAG"
                exit 1
              fi
              echo "export POM_VERSION_NAME=$POM_VERSION_NAME" >> $BASH_ENV
            fi

  run-firebase-instrumentation:
    parameters:
      module_wrapper:
        description: module wrapper
        type: string
      module_target:
        description: module target
        type: string
      variant:
        description: debug or release
        type: string
    steps:
      - run:
          name: Run instrumentation tests on Firebase
          no_output_timeout: 1200
          shell: /bin/bash -euo pipefail
          command: |
            gcloud firebase test android run --type instrumentation \
              --app << parameters.module_wrapper >>/build/outputs/apk/<< parameters.variant >>/<< parameters.module_wrapper >>-<< parameters.variant >>.apk \
              --test << parameters.module_target >>/build/outputs/apk/androidTest/<< parameters.variant >>/<< parameters.module_target >>-<< parameters.variant >>-androidTest.apk \
              --device model=hammerhead,version=21,locale=en,orientation=portrait  \
              --device model=athene,version=23,locale=fr,orientation=landscape \
              --device model=sailfish,version=26,locale=es,orientation=portrait \
              --device model=walleye,version=28,locale=de,orientation=landscape \
              --use-orchestrator \
              --timeout 5m

  run-firebase-robo:
    parameters:
      variant:
        description: debug or release
        type: string
    steps:
      - run:
          name: Run robo tests on Firebase
          no_output_timeout: 10m
          command: |
            gcloud firebase test android run --type robo \
              --app examples/build/outputs/apk/<< parameters.variant >>/examples-<< parameters.variant >>.apk \
              --device model=hammerhead,version=21,locale=en,orientation=portrait  \
              --device model=athene,version=23,locale=fr,orientation=landscape \
              --device model=sailfish,version=26,locale=es,orientation=portrait \
              --device model=walleye,version=28,locale=de,orientation=landscape \
              --timeout 5m

  publish-artifacts:
    parameters:
      artifact-type:
        description: core or ui
        type: string
    steps:
      - deploy:
          name: Upload Navigation SDK to SDK Registry
          command: |
            make << parameters.artifact-type >>-upload-to-sdk-registry

  check-public-documentation:
    steps:
      - run:
          name: Check public documentation
          command: sh scripts/dokka-validate.sh

  generate-documentation:
    steps:
      - run:
          name: Generate documentation
          command: make javadoc-dokka

  track-performance:
    steps:
      - run:
          name: Track performance of the Navigation SDK
          command: |
            if [ -n "${MOBILE_METRICS_TOKEN}" ]; then
              if [[ $CIRCLE_BRANCH == master ]]; then
               curl -u ${MOBILE_METRICS_TOKEN}: \
                 -d build_parameters[CIRCLE_JOB]=android-navigation-benchmark \
                 -d build_parameters[BENCHMARK_COMMIT]= ${CIRCLE_SHA1} \
                 https://circleci.com/api/v1.1/project/github/mapbox/mobile-metrics/tree/master
              fi
            fi
      - run:
          name: Trigger android binary size check
          command: |
            if [ -n "${MOBILE_METRICS_TOKEN}" ]; then
              if [[ $CIRCLE_BRANCH == master ]]; then
                curl -u ${MOBILE_METRICS_TOKEN}: -d build_parameters[CIRCLE_JOB]=android-navigation-binary-size https://circleci.com/api/v1.1/project/github/mapbox/mobile-metrics/tree/master
              fi
            fi
      - run:
          name: Trigger code coverage check
          command: |
            if [ -n "${MOBILE_METRICS_TOKEN}" ]; then
              if [[ $CIRCLE_BRANCH == master ]]; then
                curl -u ${MOBILE_METRICS_TOKEN}: -d build_parameters[CIRCLE_JOB]=android-navigation-code-coverage https://circleci.com/api/v1.1/project/github/mapbox/mobile-metrics/tree/master
              fi
            fi

jobs:
  assemble-debug:
    working_directory: ~/code
    docker:
      - image: << pipeline.parameters.docker-image-tag >>
    steps:
      - checkout
      - assemble-core-debug
      - assemble-ui-debug

  assemble-release:
    working_directory: ~/code
    docker:
      - image: << pipeline.parameters.docker-image-tag >>
    steps:
      - checkout
      - assemble-core-release
      - assemble-ui-release

  unit-tests:
    working_directory: ~/code
    docker:
      - image: << pipeline.parameters.docker-image-tag >>
    steps:
      - checkout
      - unit-tests-core
      - unit-tests-ui
      - codecov

  static-analysis:
    working_directory: ~/code
    docker:
      - image: << pipeline.parameters.docker-image-tag >>
    steps:
      - checkout
      - restore-gradle-cache
      - verify
      - check-api-core
      - check-api-ui
      - check-public-documentation

  ui-robo-tests:
    docker:
      - image: << pipeline.parameters.docker-image-tag >>
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
      BUILDTYPE: Debug
      GRADLE_OPTS: -Xmx4096m -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process
    steps:
      - checkout
      - restore-gradle-cache
      - assemble-example-app:
          variant: "Release"
      - login-google-cloud-platform
      - run-firebase-robo:
          variant: "release"

  ui-instrumentation-tests:
    docker:
      - image: << pipeline.parameters.docker-image-tag >>
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
      BUILDTYPE: Debug
      GRADLE_OPTS: -Xmx4096m -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process
    steps:
      - checkout
      - restore-gradle-cache
      - assemble-module:
          module_target: "app-tests-wrapper"
          variant: "Debug"
      - assemble-module:
          module_target: "libnavigation-core"
          variant: "Debug"
      - assemble-instrumentation-test:
          module_target: "libnavigation-core"
      - login-google-cloud-platform
      - run-firebase-instrumentation:
          module_target: "libnavigation-core"
          module_wrapper: "app-tests-wrapper"
          variant: "debug"

  release-snapshot:
    working_directory: ~/code
    docker:
      - image: << pipeline.parameters.docker-image-tag >>
    steps:
      - checkout
      - generate-version-name
      - assemble-core-release
      - assemble-ui-release
      - check-public-documentation
      - generate-documentation
      - publish-artifacts:
          artifact-type: "core"
      - publish-artifacts:
          artifact-type: "ui"
      - track-performance

  release:
    working_directory: ~/code
    docker:
      - image: << pipeline.parameters.docker-image-tag >>
    steps:
      - checkout
      - generate-version-name
      - assemble-core-release
      - assemble-ui-release
      - check-public-documentation
      - generate-documentation
      - publish-artifacts:
          artifact-type: "core"
      - publish-artifacts:
          artifact-type: "ui"
