enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include ':app-tests-wrapper',
        ':dispatchers',
        ':instrumentation-tests',
        ':libnavigation-android',
        ':navigator',
        ':base',
        ':metrics',
        ':notification',
        ':utils',
        ':navigation',
        ':copilot',
        ':tripdata',
        ':voice',
        ':libtesting-dispatchers',
        ':libtesting-ui',
        ':libtesting-utils',
        ':ui-base',
        ':ui-maps',
        ':ui-utils',
        ':libnavui-resources',
        ':libtesting-thirdparty',
        ':libtesting-router',
        ':libtesting-navigation-base',
        ':libtesting-navigation-util',
        ':libtesting-navigation-core-utils',
        ':libtesting-resources',
        ':search',
        ':androidauto',
        ':ui-components',
        ':driver-notification'
