version: 2.1
orbs:
  android: circleci/android@2.0.3

parameters:
  mapbox_navigation_native_upstream:
    type: boolean
    default: false
  mapbox_navigation_native_snapshot:
    type: string
    default: ''

#-------------------------------
#---------- EXECUTORS ----------
#-------------------------------
executors:
  helsinki-bmw_bench:
    resource_class: mapbox/helsinki-bmw_bench
    machine: true
    working_directory: ~/code
    environment:
      MBX_CI_DOMAIN: o619qyc20d.execute-api.us-east-1.amazonaws.com
      FORCE_MAPBOX_NAVIGATION_NATIVE_VERSION: << pipeline.parameters.mapbox_navigation_native_snapshot >>
      ALLOW_SNAPSHOT_REPOSITORY: << pipeline.parameters.mapbox_navigation_native_upstream >>
#-------------------------------
#---------- WORKFLOWS ----------
#-------------------------------
workflows:
  version: 2
  default:
    jobs:
      - instrumentation-tests
#------------------------------
#---------- COMMANDS ----------
#------------------------------
commands:
  write-workspace:
    steps:
      - persist_to_workspace:
          root: ~/code
          paths:
            - ./
  read-workspace:
    steps:
      - attach_workspace:
          at: ~/code

  store-results:
    parameters:
      module_target:
        description: module target
        type: string
    steps:
      - run:
          name: Save logcat
          command: |
            adb logcat -d > instrumentation-tests/build/reports/camera-crash.log
      - store_artifacts:
          path: << parameters.module_target >>/build/reports
          destination: << parameters.module_target >>/reports
      - store_test_results:
          path: << parameters.module_target >>/build/test-results

  run-firebase-instrumentation:
    steps:
      - run:
          name: Prepare report folders
          command: |
            mkdir -p instrumentation-tests/build/reports/
      - run:
          name: Run instrumentation tests
          continue-on-error: true
          no_output_timeout: 1200
          shell: /bin/bash -euo pipefail
          command: |
            ./gradlew :instrumentation-tests:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.mapbox.navigation.instrumentation_tests.core.CoreRerouteTest -i

  prepare-mbx-ci:
    steps:
      - run:
          name: Install mbx-ci
          command: |
            curl -Ls https://mapbox-release-engineering.s3.amazonaws.com/mbx-ci/latest/mbx-ci-linux-amd64 > mbx-ci && chmod 755 ./mbx-ci

  setup-aws-credentials:
    steps:
      - run:
          name: Obtain AWS credentials
          command: |
            ./mbx-ci aws setup

#--------------------------
#---------- JOBS ----------
#--------------------------
jobs:
  instrumentation-tests:
    executor: helsinki-bmw_bench
    environment:
      JVM_OPTS: -Xmx3200m
      BUILDTYPE: Debug
      GRADLE_OPTS: -Xmx4096m -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process
    steps:
      - when:
          condition:
            not:
              matches:
                pattern: "^add-changelog.*"
                value: << pipeline.git.branch >>
          steps:
            - checkout
            - read-workspace
            - run-firebase-instrumentation
            - store-results:
                module_target: "instrumentation-tests"
      - run: exit 0
