package com.mapbox.navigation.base.route

import androidx.annotation.StringDef
import com.mapbox.navigation.base.ExperimentalMapboxNavigationAPI

/**
 * Describes API which generated data for [NavigationRoute].
 */
@StringDef(
    ResponseOriginAPI.DIRECTIONS_API,
    ResponseOriginAPI.MAP_MATCHING_API,
)
@Retention(AnnotationRetention.BINARY)
@ExperimentalMapboxNavigationAPI
annotation class ResponseOriginAPI {
    companion object {
        /**
         * [NavigationRoute] was built based on response generated by
         * [Mapbox Directions API](https://docs.mapbox.com/api/navigation/directions/)
         * if [NavigationRoute.origin] is [RouterOrigin.ONLINE]
         * or by an onboard router
         * if [NavigationRoute.origin] is [RouterOrigin.OFFLINE].
         */
        @ExperimentalMapboxNavigationAPI
        const val DIRECTIONS_API = "DIRECTIONS_API"

        /**
         * [NavigationRoute] was build based on response generated by
         * [Mapbox Map Matching API](https://docs.mapbox.com/api/navigation/map-matching/),
         * [NavigationRoute.origin] is always [RouterOrigin.ONLINE] for [MAP_MATCHING_API].
         *
         * Navigation experience is limited for routes from [MAP_MATCHING_API] in comparison to
         * routes from [DIRECTIONS_API]. Route refresh and reroute aren't supported.
         */
        @ExperimentalMapboxNavigationAPI
        const val MAP_MATCHING_API = "MAP_MATCHING_API"
    }
}
