package com.mapbox.navigation.base.options

import com.mapbox.navigation.base.ExperimentalMapboxNavigationAPI

/**
 * Indicates which reroute strategy is applied for routes generated by Mapbox Map Matching API.
 */
@ExperimentalMapboxNavigationAPI
abstract class RerouteStrategyForMapMatchedRoutes internal constructor()

/**
 *  Reroute is disabled for routes generated by Mapbox Map Matching API.
 */

@OptIn(ExperimentalMapboxNavigationAPI::class)
object RerouteDisabled : RerouteStrategyForMapMatchedRoutes()

/**
 * Navigation SDK will build a route to the final destination using the last waypoint from
 * [NavigationRoute.waypoints].
 */

@OptIn(ExperimentalMapboxNavigationAPI::class)
object NavigateToFinalDestination : RerouteStrategyForMapMatchedRoutes()
