@file:OptIn(ExperimentalSerializationApi::class)

package com.mapbox.navigation.voicefeedback.internal

import com.mapbox.navigation.base.ExperimentalPreviewMapboxNavigationAPI
import kotlinx.serialization.DeserializationStrategy
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.descriptors.element
import kotlinx.serialization.encodeToString
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.encodeToJsonElement
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/**
 * Session frame koin serializer module
 */
@OptIn(ExperimentalPreviewMapboxNavigationAPI::class)
internal val sessionFrameSerializerModule = SerializersModule {

    // TODO add correct round-tripping of unknown polymorphic types,
    //  right now the unknown types encode non-abstract fields in a separate 'details' JSON object
    //  when they are serialized back to JSON

    polymorphic(baseClass = SessionFrame::class) {
        subclass(SessionFrame.SendEvent::class)
        subclass(SessionFrame.StartSession::class)
        subclass(SessionFrame.Unknown::class)
        default {
            SessionFrame.Unknown.UnknownDeserializationStrategy
        }
    }
    polymorphic(baseClass = SessionFrame.SendEvent.Body::class) {
        subclass(SessionFrame.SendEvent.Body.Conversation::class)
        subclass(SessionFrame.SendEvent.Body.NoResponse::class)
        subclass(SessionFrame.SendEvent.Body.StopListening::class)
        subclass(SessionFrame.SendEvent.Body.Feedback::class)
        subclass(SessionFrame.SendEvent.Body.Unknown::class)
        default {
            SessionFrame.SendEvent.Body.Unknown.UnknownDeserializationStrategy
        }
    }
    polymorphic(baseClass = OutgoingSessionFrame::class) {
        subclass(OutgoingSessionFrame.GetSessionId::class)
    }
}

@OptIn(ExperimentalSerializationApi::class)
private val jsonSerialization = Json {
    serializersModule = sessionFrameSerializerModule
    explicitNulls = false
    ignoreUnknownKeys = true
}

/**
 * Definition of a frame that carries information across the communication channel with Feedback Agent backend.
 */
@ExperimentalPreviewMapboxNavigationAPI
@Serializable
@JsonClassDiscriminator(discriminator = "action")
internal abstract class SessionFrame {

    /**
     * Definition of an event that is generated by the server when certain things happen, such as extracting a POI from a user / assistant conversation.
     *
     * @param body contents of the event
     */
    @Serializable
    @SerialName("send-event")
    data class SendEvent(
        val body: Body,
    ) : SessionFrame() {

        /**
         * Defines the event specifics, which varies based on the event type.
         */
        @Serializable
        abstract class Body {

            /**
             * A unique increasing ID field for the event. This can be used by the client to reference the last received event ID when reconnecting to the service.
             *
             * @see [FeedbackAgentService.connect]
             */
            abstract val id: Long

            /**
             * Creation type of the event as a unix timestamp
             */
            abstract val timestamp: Long

            /**
             * Describes which conversational chunk the event is tied to, in format of `{date}@{id}`
             * where the [chunkPrefix] should be considered as an ID of the AI response
             * and [chunkOffset] is the logical order in the response stream.
             */
            @SerialName("chunk_id")
            abstract val chunkId: String

            /**
             * Represents an ID of the AI response.
             *
             * See [chunkId].
             */
            val chunkPrefix: String by lazy { chunkId.split("@").first() }

            /**
             * Represents logical order in the response stream.
             *
             * See [chunkId].
             */
            val chunkOffset: Int by lazy { chunkId.split("@")[1].toInt() }

            /**
             * Defines events that were not generated in direct response to user query
             * but retroactively or spontaneously by the assistant.
             */
            @SerialName("is_supplement")
            abstract val isSupplement: Boolean

            /**
             * Defines a conversation chunk. A single chunk is typically a sentence in a longer AI response.
             *
             * Conversation can be in direct response to something the user said or may be sent separately, e.g., after processing a restaurant reservation request.
             *
             * @param data conversation contents
             */
            @Serializable
            @SerialName("conversation")
            data class Conversation(
                override val id: Long,
                override val timestamp: Long,
                @SerialName("chunk_id")
                override val chunkId: String,
                @SerialName("is_supplement")
                override val isSupplement: Boolean = false,
                val data: Data,
            ) : Body() {

                /**
                 * Conversation contents.
                 *
                 * @param conversationId a unique string for this conversation
                 * @param content the sentence in a response
                 * @param initial whether this is the first chunk in the response stream
                 * @param confirmation whether this chunk is a confirmation of a user action
                 * @param final whether this is the last chunk in the response stream
                 * @param maxTokens whether conversation has hit the profile's response token limit
                 */
                @Serializable
                data class Data(
                    @SerialName("conversation_id")
                    val conversationId: String,
                    val content: String,
                    val initial: Boolean = false,
                    val confirmation: Boolean = false,
                    val final: Boolean = false,
                    @SerialName("max_tokens")
                    val maxTokens: Boolean = false,
                )
            }

            /**
             * Defines action containing no verbal response for the user query.
             */
            @Serializable
            @SerialName("no_response")
            data class NoResponse(
                override val id: Long,
                override val timestamp: Long,
                @SerialName("chunk_id")
                override val chunkId: String,
                @SerialName("is_supplement")
                override val isSupplement: Boolean = false,
            ) : Body()

            /**
             * Defines action ordering Feedback Agent to close the microphone and stop capturing input.
             */
            @Serializable
            @SerialName("stop_listening")
            data class StopListening(
                override val id: Long,
                override val timestamp: Long,
                @SerialName("chunk_id")
                override val chunkId: String,
                @SerialName("is_supplement")
                override val isSupplement: Boolean = false,
            ) : Body()

            /**
             * Represents a user feedback event.
             *
             * This event stores details about user feedback, including metadata and feedback content.
             *
             * @property id The unique identifier of the event.
             * @property timestamp The timestamp of when the event occurred.
             * @property chunkId The associated chunk identifier.
             * @property isSupplement Indicates whether this event is a supplemental entry.
             * @property data The feedback-specific data.
             */
            @Serializable
            @SerialName("feedback")
            data class Feedback(
                override val id: Long,
                override val timestamp: Long,
                @SerialName("chunk_id")
                override val chunkId: String,
                @SerialName("is_supplement")
                override val isSupplement: Boolean = false,
                val data: Data,
            ) : Body() {

                /**
                 * Represents the feedback-specific data.
                 *
                 * @property feedbackType The category or type of feedback (e.g., bug report, suggestion).
                 * @property feedbackDescription The detailed description of the feedback.
                 */
                @Serializable
                data class Data(
                    @SerialName("feedbackType")
                    val feedbackType: String,
                    @SerialName("feedbackDescription")
                    val feedbackDescription: String,
                )
            }

            /**
             * Payload associated with unknown types.
             *
             * @param details map of key value pairs
             */
            @Serializable
            data class Unknown(
                override val id: Long,
                override val timestamp: Long,
                @SerialName("chunk_id")
                override val chunkId: String,
                @SerialName("is_supplement")
                override val isSupplement: Boolean = false,
                val details: Map<String, JsonElement>,
            ) : Body() {

                internal object UnknownDeserializationStrategy : DeserializationStrategy<Unknown> {

                    override val descriptor: SerialDescriptor =
                        buildClassSerialDescriptor("Unknown") {
                            element<Long>("id")
                            element<Long>("timestamp")
                            element<String>("chunk_id")
                            element<Boolean>("is_supplement")
                            element<JsonObject>("details")
                        }

                    override fun deserialize(decoder: Decoder): Unknown {
                        val jsonInput = decoder as? JsonDecoder
                            ?: error("Can be deserialized only by JSON")
                        val json = jsonInput.decodeJsonElement().jsonObject
                        val id = json.getValue("id").jsonPrimitive.content.toLong()
                        val timestamp = json.getValue("timestamp").jsonPrimitive.content.toLong()
                        val chunkId = json.getValue("chunk_id").jsonPrimitive.content
                        val isSupplement = json["is_supplement"]
                            ?.jsonPrimitive?.contentOrNull?.toBooleanStrictOrNull() ?: false
                        val details = json.toMutableMap()
                        details.remove("id")
                        details.remove("timestamp")
                        details.remove("chunk_id")
                        details.remove("is_supplement")
                        return Unknown(
                            id = id,
                            timestamp = timestamp,
                            chunkId = chunkId,
                            isSupplement = isSupplement,
                            details = details,
                        )
                    }
                }
            }
        }
    }

    /**
     * Called when a connection with the backend service is established and a new session is started.
     *
     * @param body content associated with the session
     */
    @Serializable
    @SerialName("start-session")
    data class StartSession(
        val body: Body,
    ) : SessionFrame() {

        /**
         * Content associated with the session
         *
         * @param sessionId session id
         */
        @Serializable
        data class Body(
            @SerialName("session_id")
            val sessionId: String,
        )
    }

    /**
     * Payload associated with unknown types.
     *
     * @param details map of key value pairs
     */
    @Serializable
    data class Unknown(
        val details: Map<String, JsonElement>,
    ) : SessionFrame() {

        internal object UnknownDeserializationStrategy : DeserializationStrategy<Unknown> {

            override val descriptor: SerialDescriptor =
                buildClassSerialDescriptor("Unknown") {
                    element<JsonObject>("details")
                }

            override fun deserialize(decoder: Decoder): Unknown {
                val jsonInput = decoder as? JsonDecoder
                    ?: error("Can be deserialized only by JSON")
                val json = jsonInput.decodeJsonElement().jsonObject
                val details = json.toMutableMap()
                return Unknown(
                    details = details,
                )
            }
        }
    }

    /**
     * Encode the object to JSON string.
     */
    fun toJsonString(): String {
        return jsonSerialization.encodeToJsonElement(this).toString()
    }

    companion object {

        /**
         * Decode the object from JSON string.
         */
        fun fromJsonString(json: String): SessionFrame {
            return jsonSerialization.decodeFromString(json)
        }
    }
}

@Serializable
@JsonClassDiscriminator(discriminator = "action")
internal abstract class OutgoingSessionFrame {

    @Serializable
    @SerialName("get-session-id")
    internal class GetSessionId : OutgoingSessionFrame()

    fun toJsonString(): String {
        return jsonSerialization.encodeToString(this)
    }

    companion object {

        fun fromJsonString(json: String): OutgoingSessionFrame {
            return jsonSerialization.decodeFromString(json)
        }
    }
}
