package com.mapbox.navigation.ui.maps.internal.route.callout.api

import android.view.View
import androidx.annotation.RestrictTo
import com.mapbox.maps.MapboxMap
import com.mapbox.maps.SourceDataLoadedType
import com.mapbox.maps.ViewAnnotationAnchorConfig
import com.mapbox.maps.viewannotation.OnViewAnnotationUpdatedListener
import com.mapbox.maps.viewannotation.ViewAnnotationManager
import com.mapbox.maps.viewannotation.annotatedLayerFeature
import com.mapbox.navigation.base.ExperimentalPreviewMapboxNavigationAPI
import com.mapbox.navigation.ui.maps.internal.route.callout.model.RouteCalloutData
import com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils
import com.mapbox.navigation.ui.maps.route.callout.api.MapboxRouteCalloutAdapter
import com.mapbox.navigation.ui.maps.route.callout.api.RouteCalloutUiState
import com.mapbox.navigation.ui.maps.route.callout.api.RouteCalloutUiStateData
import com.mapbox.navigation.ui.maps.route.callout.model.CalloutViewHolder
import com.mapbox.navigation.ui.maps.route.callout.model.RouteCallout
import com.mapbox.navigation.utils.internal.logD

@OptIn(ExperimentalPreviewMapboxNavigationAPI::class)
internal typealias PendingCallout = Pair<RouteCalloutUiState, String>

/**
 * Responsible for rendering data generated by the [MapboxRouteCalloutsApi] class. The
 * data will change the appearance/behaviour of the route callout(s) on the map.
 */
@OptIn(ExperimentalPreviewMapboxNavigationAPI::class)
@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP_PREFIX)
class MapboxRouteCalloutsView(
    private val viewAnnotationManager: ViewAnnotationManager,
    private val routeCalloutAdapter: MapboxRouteCalloutAdapter,
    private val map: MapboxMap? = null,
) {

    private var routeCalloutResult: RouteCalloutUiStateData? = null

    // A callout DVA is positioned by querying the rendered features of its route-line layer. If a
    // callout is attached before its route source is rendered, the anchor can't resolve and the
    // callout stays invisible until something forces a re-query.
    // So each callout that has not been placed yet is tracked here, together with the source its
    // layer draws from. When that source reports a new version of its data, the callout is
    // re-attached, which makes the map query the fresh features.
    private val pendingCallouts = mutableMapOf<View, PendingCallout>()

    // Layer id to the id of the source it draws from, retrieved from the style. Only used for
    // layers that are not part of [routeLineLayersToSources].
    private val styleResolvedSources = mutableMapOf<String, String>()

    private val currentLayersToAttach = mutableSetOf<String>()

    // Tracked directly since annotations are now keyed by (layerId, featureId), not layerId alone.
    private val currentViews = mutableListOf<View>()

    private val onViewAnnotationUpdatedListener = object : OnViewAnnotationUpdatedListener {
        override fun onViewAnnotationAnchorUpdated(
            view: View,
            anchor: ViewAnnotationAnchorConfig,
        ) {
            val placed = pendingCallouts.remove(view)
            logD(TAG) {
                "onViewAnnotationAnchorUpdated, placed layer: ${placed?.first?.layerId}, " +
                    "still awaiting placement: ${pendingCallouts.size}"
            }

            routeCalloutAdapter.onUpdateAnchor(view, anchor)
        }
    }

    private val dataChangedObserver: () -> Unit = {
        routeCalloutResult?.let { renderCallouts(it) }
    }

    private val sourceDataLoadedSubscription = map?.subscribeSourceDataLoaded { eventData ->
        if (eventData.type != SourceDataLoadedType.METADATA) {
            return@subscribeSourceDataLoaded
        }

        val sourceId = eventData.sourceId
        if (pendingCallouts.values.any { it.second == sourceId }) {
            logD(TAG) { "Source data loaded: $sourceId, re-attaching pending callouts" }
            reattachPendingCallouts(sourceId)
        }
    }

    init {
        viewAnnotationManager.addOnViewAnnotationUpdatedListener(onViewAnnotationUpdatedListener)
        routeCalloutAdapter.registerDataObserver(dataChangedObserver)
    }

    /**
     * Renders [RouteCalloutData]
     */
    fun renderCallouts(
        routeCalloutResult: RouteCalloutUiStateData,
    ) {
        logD(TAG) {
            "renderCallouts"
        }

        this.routeCalloutResult = routeCalloutResult
        clear()

        val addViewAnnotationJobs = mutableListOf<() -> Unit>()

        routeCalloutResult.callouts.forEach { calloutRoute ->
            val viewHolder = createViewHolder(calloutRoute.routeCallout)
            currentLayersToAttach.add(calloutRoute.layerId)
            // first set viewAnnotationAvoidLayers, then execute the jobs to avoid flickering
            addViewAnnotationJobs.add({ addViewAnnotation(calloutRoute, viewHolder) })
        }
        viewAnnotationManager.viewAnnotationAvoidLayers = HashSet(
            viewAnnotationManager.viewAnnotationAvoidLayers + currentLayersToAttach,
        )
        addViewAnnotationJobs.forEach { it() }
    }

    fun release() {
        this.routeCalloutResult = null
        styleResolvedSources.clear()
        sourceDataLoadedSubscription?.cancel()
        clear()
        viewAnnotationManager.removeOnViewAnnotationUpdatedListener(onViewAnnotationUpdatedListener)
        routeCalloutAdapter.removeDataObserver(dataChangedObserver)
    }

    private fun addViewAnnotation(
        calloutState: RouteCalloutUiState,
        viewHolder: CalloutViewHolder,
    ) {
        val layerId = calloutState.layerId
        val options = viewHolder.options.toBuilder()
            .annotatedLayerFeature(layerId) {
                // Scopes to this route's feature so a reused layer slot can't resolve to a
                // stale route's geometry.
                featureId(calloutState.routeCallout.route.id)
            }
            .build()

        val sourceId = sourceIdOfLayer(layerId)
        logD(TAG) {
            "sourceIdOfLayer($layerId) is $sourceId"
        }
        if (sourceId != null) {
            pendingCallouts[viewHolder.view] = PendingCallout(calloutState, sourceId)
        } else {
            logD(TAG) {
                "The source of layer $layerId is unknown, " +
                    "the callout will not self-heal if its first placement fails"
            }
        }
        currentViews.add(viewHolder.view)
        viewAnnotationManager.addViewAnnotation(
            view = viewHolder.view,
            options = options,
        )
    }

    private fun reattachPendingCallouts(sourceId: String) {
        pendingCallouts.filterValues { it.second == sourceId }.forEach { (view, pending) ->
            pendingCallouts.remove(view)
            viewAnnotationManager.removeViewAnnotation(view)
            currentViews.remove(view)
            addViewAnnotation(pending.first, createViewHolder(pending.first.routeCallout))
        }
    }

    private fun clear() {
        currentViews.forEach { viewAnnotationManager.removeViewAnnotation(it) }
        currentViews.clear()
        viewAnnotationManager.viewAnnotationAvoidLayers =
            HashSet(viewAnnotationManager.viewAnnotationAvoidLayers - currentLayersToAttach)
        currentLayersToAttach.clear()
        pendingCallouts.clear()
    }

    private fun createViewHolder(callout: RouteCallout): CalloutViewHolder {
        val viewHolder = routeCalloutAdapter.onCreateViewHolder(callout)

        return viewHolder
    }

    private fun sourceIdOfLayer(layerId: String): String? {
        routeLineLayersToSources[layerId]?.let { return it }
        styleResolvedSources[layerId]?.let { return it }
        val sourceId = try {
            map?.style?.getStyleLayerProperty(layerId, "source")?.value?.contents as? String
        } catch (e: RuntimeException) {
            logD(TAG) {
                "Unable to resolve source for layer $layerId: ${e.message}"
            }
            null
        }
        return sourceId?.also { styleResolvedSources[layerId] = it }
    }

    private companion object {

        const val TAG = "MapboxRouteCalloutsView"

        val routeLineLayersToSources: Map<String, String> =
            MapboxRouteLineUtils.sourceLayerMap.entries
                .flatMap { (sourceKey, layerIds) -> layerIds.map { it to sourceKey.sourceId } }
                .toMap()
    }
}
