package com.mapbox.navigation.ui.maps.route.callout.api

import android.view.View
import com.mapbox.maps.MapView
import com.mapbox.maps.ViewAnnotationAnchor
import com.mapbox.maps.ViewAnnotationAnchorConfig
import com.mapbox.maps.logW
import com.mapbox.maps.viewannotation.OnViewAnnotationUpdatedListener
import com.mapbox.maps.viewannotation.annotatedLayerFeature
import com.mapbox.maps.viewannotation.annotationAnchors
import com.mapbox.maps.viewannotation.viewAnnotationOptions
import com.mapbox.navigation.base.ExperimentalPreviewMapboxNavigationAPI
import com.mapbox.navigation.base.route.NavigationRoute
import com.mapbox.navigation.ui.maps.internal.route.callout.model.RouteCallout
import com.mapbox.navigation.ui.maps.route.RouteLayerConstants
import com.mapbox.navigation.ui.maps.route.callout.model.MapboxRouteCalloutViewOptions
import com.mapbox.navigation.ui.maps.route.callout.model.RouteCalloutData
import com.mapbox.navigation.ui.maps.route.callout.view.RouteCalloutView
import com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineView

/**
 * Responsible for rendering data generated by the [MapboxRouteCalloutApi] class. The
 * data will change the appearance/behaviour of the route callout(s) on the map.
 *
 * @param mapView the instance of [MapView]
 * @param options used for determining the appearance of the route callouts
 */
@ExperimentalPreviewMapboxNavigationAPI
class MapboxRouteCalloutView(
    private val mapView: MapView,
    options: MapboxRouteCalloutViewOptions = MapboxRouteCalloutViewOptions.Builder().build(),
) {

    private var viewOptions: MapboxRouteCalloutViewOptions = options
    private var routeCalloutClickListener: ((NavigationRoute) -> Unit)? = null
    private val viewAnnotationManager = mapView.viewAnnotationManager
    private val routeCallouts: MutableList<RouteCalloutView> = mutableListOf()
    private val onViewAnnotationUpdatedListener = object : OnViewAnnotationUpdatedListener {
        override fun onViewAnnotationAnchorUpdated(
            view: View,
            anchor: ViewAnnotationAnchorConfig,
        ) {
            (view as? RouteCalloutView)?.updateAnchor(anchor)
        }
    }

    init {
        viewAnnotationManager.viewAnnotationAvoidLayers =
            HashSet(
                viewAnnotationManager.viewAnnotationAvoidLayers +
                    setOf(
                        RouteLayerConstants.LAYER_GROUP_1_MAIN,
                        RouteLayerConstants.LAYER_GROUP_2_MAIN,
                        RouteLayerConstants.LAYER_GROUP_3_MAIN,
                        RouteLayerConstants.MASKING_LAYER_MAIN,
                    ),
            )
        viewAnnotationManager.addOnViewAnnotationUpdatedListener(onViewAnnotationUpdatedListener)
    }

    /**
     * Updates options determining the appearance of the route callouts
     */
    fun updateRouteCalloutViewOptions(options: MapboxRouteCalloutViewOptions) {
        viewOptions = options
        routeCallouts.forEach { it.updateOptions(viewOptions) }
    }

    /**
     * @param listener notifies when the user clicks on a route callout
     */
    fun setRouteCalloutClickListener(listener: ((NavigationRoute) -> Unit)?) {
        routeCalloutClickListener = listener
    }

    /**
     * Renders an [RouteCalloutData]
     */
    fun renderCallouts(
        routeCalloutResult: RouteCalloutData,
        routeLineView: MapboxRouteLineView,
    ) {
        clear(routeCalloutResult.callouts)

        routeCalloutResult.callouts.forEach { calloutRoute ->
            val layer = routeLineView.getRouteMainLayerIdForFeature(calloutRoute.route.id)
            if (layer != null) {
                val view = getOrCreateRouteCalloutView(calloutRoute)
                addView(
                    layer,
                    view,
                    calloutRoute.minZoom,
                    calloutRoute.maxZoom,
                    calloutRoute.priority,
                )
            } else {
                logW(
                    TAG,
                    "Layer for route [${calloutRoute.route.id}] not found",
                )
            }
        }
    }

    private fun clear(routes: List<RouteCallout>) {
        val newIds = routes.map { it.route.id }
        val (remainingViews, removedViews) = routeCallouts.partition { newIds.contains(it.tag) }

        removedViews.forEach { viewAnnotationManager.removeViewAnnotation(it) }
        routeCallouts.clear()
        routeCallouts.addAll(remainingViews)
    }

    private fun addView(
        layerId: String,
        view: View,
        minZoom: Float?,
        maxZoom: Float?,
        priority: Long?,
    ) {
        val density = mapView.resources.displayMetrics.density
        if (viewAnnotationManager.getViewAnnotationOptions(view) == null) {
            viewAnnotationManager.addViewAnnotation(
                view = view,
                options = viewAnnotationOptions {
                    ignoreCameraPadding(true)
                    annotatedLayerFeature(layerId)
                    minZoom(minZoom)
                    maxZoom(maxZoom)
                    priority(priority)
                    annotationAnchors(
                        {
                            anchor(ViewAnnotationAnchor.TOP_RIGHT)
                            offsetX(BASE_X_OFFSET * density)
                            offsetY(BASE_Y_OFFSET * density)
                        },
                        {
                            anchor(ViewAnnotationAnchor.TOP_LEFT)
                            offsetX(-1.0 * BASE_X_OFFSET * density)
                            offsetY(BASE_Y_OFFSET * density)
                        },
                        {
                            anchor(ViewAnnotationAnchor.BOTTOM_RIGHT)
                            offsetX(BASE_X_OFFSET * density)
                            offsetY(-1.0 * BASE_Y_OFFSET * density)
                        },
                        {
                            anchor(ViewAnnotationAnchor.BOTTOM_LEFT)
                            offsetX(-1.0 * BASE_X_OFFSET * density)
                            offsetY(-1.0 * BASE_Y_OFFSET * density)
                        },
                    )
                },
            )
        }
    }

    private fun getOrCreateRouteCalloutView(callout: RouteCallout): View {
        val route = callout.route
        val view = routeCallouts.firstOrNull { it.tag == route.id }
            ?: createView(callout).also { routeCallouts.add(it) }
        view.setRouteCallout(callout)

        return view
    }

    private fun createView(
        callout: RouteCallout,
    ): RouteCalloutView {
        val view = RouteCalloutView(mapView.context, options = viewOptions)
        view.tag = callout.route.id
        view.setOnClickListener { routeCalloutClickListener?.invoke(callout.route) }
        return view
    }

    private companion object {
        private const val BASE_X_OFFSET = 7.0
        private const val BASE_Y_OFFSET = 10.0

        private const val TAG = "MapboxRouteCalloutView"
    }
}
