package com.mapbox.navigation.ui.maps.route.callout.api

import android.view.View
import com.mapbox.maps.AnnotatedLayerFeature
import com.mapbox.maps.ViewAnnotationAnchorConfig
import com.mapbox.maps.logW
import com.mapbox.maps.viewannotation.OnViewAnnotationUpdatedListener
import com.mapbox.maps.viewannotation.ViewAnnotationManager
import com.mapbox.maps.viewannotation.annotatedLayerFeature
import com.mapbox.navigation.base.ExperimentalPreviewMapboxNavigationAPI
import com.mapbox.navigation.ui.maps.route.RouteLayerConstants
import com.mapbox.navigation.ui.maps.route.callout.model.CalloutViewHolder
import com.mapbox.navigation.ui.maps.route.callout.model.RouteCallout
import com.mapbox.navigation.ui.maps.route.callout.model.RouteCalloutData
import com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineView

/**
 * Responsible for rendering data generated by the [MapboxRouteCalloutApi] class. The
 * data will change the appearance/behaviour of the route callout(s) on the map.
 */
@OptIn(ExperimentalPreviewMapboxNavigationAPI::class)
internal class MapboxRouteCalloutView(
    private val viewAnnotationManager: ViewAnnotationManager,
    private val routeCalloutAdapter: MapboxRouteCalloutAdapter,
    private val routeLineView: MapboxRouteLineView,
) {

    private var routeCalloutResult: RouteCalloutData? = null
    private val onViewAnnotationUpdatedListener = object : OnViewAnnotationUpdatedListener {
        override fun onViewAnnotationAnchorUpdated(
            view: View,
            anchor: ViewAnnotationAnchorConfig,
        ) {
            routeCalloutAdapter.onUpdateAnchor(view, anchor)
        }
    }
    private val dataChangedObserver: () -> Unit = {
        routeCalloutResult?.let { renderCallouts(it) }
    }

    init {
        viewAnnotationManager.addOnViewAnnotationUpdatedListener(onViewAnnotationUpdatedListener)
        viewAnnotationManager.viewAnnotationAvoidLayers =
            HashSet(
                viewAnnotationManager.viewAnnotationAvoidLayers + layersToAvoid,
            )
        routeCalloutAdapter.registerDataObserver(dataChangedObserver)
    }

    /**
     * Renders [RouteCalloutData]
     */
    internal fun renderCallouts(
        routeCalloutResult: RouteCalloutData,
    ) {
        this.routeCalloutResult = routeCalloutResult
        clear()

        routeCalloutResult.callouts.forEach { calloutRoute ->
            val layer = routeLineView.getRouteMainLayerIdForFeature(calloutRoute.route.id)
            if (layer != null) {
                val viewHolder = createViewHolder(calloutRoute)

                addViewAnnotation(layer, viewHolder)
            } else {
                logW(
                    TAG,
                    "Layer for route [${calloutRoute.route.id}] not found",
                )
            }
        }
    }

    internal fun release() {
        viewAnnotationManager.removeOnViewAnnotationUpdatedListener(onViewAnnotationUpdatedListener)
        routeCalloutAdapter.removeDataObserver(dataChangedObserver)
    }

    private fun addViewAnnotation(layerId: String, viewHolder: CalloutViewHolder) {
        val options = viewHolder.options.toBuilder()
            .annotatedLayerFeature(layerId)
            .build()

        viewAnnotationManager.addViewAnnotation(
            view = viewHolder.view,
            options = options,
        )
    }

    private fun clear() {
        getAllCalloutViews().forEach { viewAnnotationManager.removeViewAnnotation(it) }
    }

    private fun createViewHolder(callout: RouteCallout): CalloutViewHolder {
        val viewHolder = routeCalloutAdapter.onCreateViewHolder(callout)

        return viewHolder
    }

    private fun getAllCalloutViews(): List<View> {
        return layersToAttach.mapNotNull {
            viewAnnotationManager.getViewAnnotation(
                AnnotatedLayerFeature.Builder().layerId(it).build(),
            )
        }
    }

    private companion object {
        private val layersToAttach = listOf(
            RouteLayerConstants.LAYER_GROUP_1_MAIN,
            RouteLayerConstants.LAYER_GROUP_2_MAIN,
            RouteLayerConstants.LAYER_GROUP_3_MAIN,
        )
        private val layersToAvoid = setOf(
            RouteLayerConstants.LAYER_GROUP_1_MAIN,
            RouteLayerConstants.LAYER_GROUP_2_MAIN,
            RouteLayerConstants.LAYER_GROUP_3_MAIN,
            RouteLayerConstants.MASKING_LAYER_MAIN,
        )

        private const val TAG = "MapboxRouteCalloutView"
    }
}
